import { image_stock } from "@/assets/image_stock";
import { IShape } from "@/editor/shapes/type.shape";
import { v4 as uuidv4 } from "uuid";

const thickness = 5;

export const shapeStart = (props: Partial<IShape>): IShape => {
  return {
    id: uuidv4(),
    x: 0,
    y: 0,
    tool: "BOX",
    isBlocked: false,
    isWritingNow: false,
    fillEnabled: true,
    align: "left",
    verticalAlign: "top",
    bordersRadius: [0, 0, 0, 0],
    effects: [],
    isLocked: false,
    label: props?.tool ?? "DEFAULT",
    parentId: null,
    rotation: 0,
    fills: [],
    strokes: [],
    strokeEnabled: true,
    visible: true,
    rotate: 0,
    height: 100,
    width: 100,
    stroke: "#ffffff",
    points: [],
    strokeWidth: thickness,
    backgroundColor: "#ffffff",
    lineCap: "round",
    lineJoin: "round",
    shadowBlur: 0,
    shadowColor: "#000",
    shadowOffsetY: thickness,
    shadowOffsetX: thickness,
    shadowEnabled: false,
    shadowOpacity: thickness,
    isAllBorderRadius: false,
    borderRadius: 0,
    borderRadiusBottomLeft: 0,
    borderRadiusBottomRight: 0,
    dash: thickness,
    dashEnabled: false,
    borderRadiusTopLeft: 0,
    borderRadiusTopRight: 0,
    closed: closed ?? false,
    colorText: "black",
    fontStyle: "Roboto",
    textDecoration: "none",
    zIndex: 0,
    fontWeight: "normal",
    fontFamily: "Roboto",
    fontSize: 24,
    resolution: "landscape",
    src: image_stock,
    text: "",
    bezier: false,
    ...props,
  };
};
