import { atom } from "jotai";
import { IShape } from "../shapes/type.shape";

const Initial: IShape = {
  id: "559c1735-4e62-4c43-aa4c-246ec594ca06",
  x: 0,
  y: 0,
  tool: "DRAW",
  align: "left",
  isCreating: false,
  verticalAlign: "top",
  bordersRadius: [0, 0, 0, 0],
  effects: [],
  isLocked: false,
  label: "DRAW",
  fillContainerHeight: false,
  fillContainerWidth: false,
  layouts: [],
  parentId: null,
  rotation: 0,
  opacity: 1,
  fills: [
    {
      visible: true,
      color: "#ffffff",
      opacity: 1,
      type: "fill",
      id: "559c1735-4e62-4c43-aa4c-246ec594ca06",
      image: {
        src: "",
        height: 100,
        name: "",
        width: 100,
      },
    },
  ],
  strokes: [
    {
      id: "559c1735-4e62-4c43-aa4c-246ec594ca06",
      visible: true,
      color: "#28a0f0",
    },
  ],
  visible: true,
  height: 100,
  width: 100,
  points: [],
  strokeWidth: 5,
  backgroundColor: "#ffffff",
  lineCap: "round",
  lineJoin: "round",
  shadowBlur: 0,
  shadowOffsetY: 5,
  shadowOffsetX: 5,
  shadowOpacity: 1,
  isAllBorderRadius: false,
  borderRadius: 0,
  dash: 0,
  fontStyle: "Roboto",
  textDecoration: "none",
  zIndex: 0,
  fontWeight: "normal",
  fontFamily: "Roboto",
  fontSize: 24,
  text: "",
};
export const DRAW_START_CONFIG_ATOM = atom(Initial);
