import { atom } from "jotai";
import { IShape } from "../shapes/type.shape";

export const DrawingBeforeStartAtom = atom({
  id: "559c1735-4e62-4c43-aa4c-246ec594ca06",
  x: 0,
  y: 0,
  tool: "DRAW",
  isBlocked: false,
  isWritingNow: false,
  fillEnabled: true,
  align: "left",
  verticalAlign: "top",
  bordersRadius: [0, 0, 0, 0],
  effects: [],
  isLocked: false,
  label: "DRAW",
  parentId: null,
  rotation: 0,
  opacity: 1,
  fills: [
    {
      visible: true,
      color: "#ffffff",
      opacity: 1,
    },
  ],
  strokes: [
    {
      visible: true,
      color: "#28a0f0",
    },
  ],
  strokeEnabled: true,
  visible: true,
  rotate: 0,
  height: 100,
  width: 100,
  stroke: "#28a0f0",
  points: [],
  strokeWidth: 5,
  backgroundColor: "#ffffff",
  lineCap: "round",
  lineJoin: "round",
  shadowBlur: 0,
  shadowColor: "#000",
  shadowOffsetY: 0,
  shadowOffsetX: 0,
  shadowEnabled: false,
  shadowOpacity: 1,
  isAllBorderRadius: false,
  borderRadius: 0,
  dash: 0,
  dashEnabled: false,
  closed: false,
  colorText: "black",
  fontStyle: "Roboto",
  textDecoration: "none",
  zIndex: 0,
  fontWeight: "normal",
  fontFamily: "Roboto",
  fontSize: 24,
  resolution: "landscape",
  src: "",
  text: "",
  bezier: true,
  color: "#28a0f0",
  thickness: 5,
  dashEnable: false,
} as IShape);
