import { atom } from "jotai";
import { IShape } from "../shapes/type.shape";

const Initial: Omit<IShape, "children"> = {
  id: "559c1735-4e62-4c43-aa4c-246ec594ca06",
  x: 0,
  y: 0,
  tool: "DRAW",
  align: "left",
  verticalAlign: "top",
  paddingBottom: 10,
  paddingTop: 10,
  borderBottomLeftRadius: 0,
  isAllPadding: true,
  borderBottomRightRadius: 0,
  borderTopLeftRadius: 0,
  borderTopRightRadius: 0,
  paddingLeft: 10,
  padding: 10,
  paddingRight: 10,
  maxHeight: 0,
  maxWidth: 0,
  minHeight: 0,
  minWidth: 0,
  effects: [],
  isLocked: false,
  label: "Draw",
  fillContainerHeight: false,
  fillContainerWidth: false,
  isLayout: false,
  alignItems: "flex-start",
  flexDirection: "row",
  flexWrap: "nowrap",
  justifyContent: "flex-start",
  gap: 10,
  parentId: null,
  rotation: 0,
  opacity: 1,
  fills: [
    {
      visible: true,
      color: "#ffffff",
      opacity: 1,
      type: "fill",
      id: "559c1735-4e62-4c43-aa4c-246ec594ca06",
      image: {
        src: "",
        height: 100,
        name: "",
        width: 100,
      },
    },
  ],
  strokes: [
    {
      id: "559c1735-4e62-4c43-aa4c-246ec594ca06",
      visible: true,
      color: "#28a0f0",
    },
  ],
  visible: true,
  height: 100,
  width: 100,
  points: [],
  strokeWidth: 1,
  lineCap: "round",
  lineJoin: "round",
  shadowBlur: 0,
  shadowOffsetY: 1,
  shadowOffsetX: 1,
  shadowOpacity: 1,
  isAllBorderRadius: false,
  borderRadius: 0,
  dash: 0,
  fontStyle: "Roboto",
  textDecoration: "none",
  fontWeight: "normal",
  fontFamily: "Roboto",
  fontSize: 24,
  text: "",
};
export const DRAW_START_CONFIG_ATOM = atom(Initial);
